version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t dependencies
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd dependencies
      - zip -r9 ../aws_lambda_artifact.zip .
      - cd ..
      - zip -g aws_lambda_artifact.zip main.py
      - zip -g aws_lambda_artifact.zip books.json
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name fastApiTest_20231028 --zip-file fileb://aws_lambda_artifact.zip
      - echo "DONE!!"